<?php

session_start();

// put full path to Smarty.class.php
require '../vendor/autoload.php';
$smarty = new Smarty();

$smarty->setTemplateDir('../smarty/templates/eu2014');
$smarty->setCompileDir('../smarty/templates_c');

//get the utm (campaign) links
// http://www.mequoda.com/articles/subscription_websites/the-mysterious-utm-code-explained/
$us = ['source', 'medium', 'campaign', 'unique'];
$utms = [];
foreach ($us as $u) {
    if (isset($_GET['utm_'.$u])) {
        $utms[$u] = sanitize(($_GET['utm_'.$u]));
    }
}
$data['utm'] = $utms;

$data['sex'] = [
  ['woman', 'Ženski'],
  ['man', ' Muški'],
];

$data['education'] = [
  ['primary', 'Osnovno'],
  ['secondary', 'Srednjoškosko'],
  ['terciary', 'Fakultetsko'],
  ['other', 'Ostalo'],
];

$data['nationality'] = [
  ['bosnian', 'Bošnjak'],
  ['serbian', 'Srbin'],
  ['croatian', 'Hrvat'],
  ['other', 'Ostali'],
];

$data['municipality'] = [
['izaberite-opstinu', 'Izaberite opštinu'],
['banovici', 'Banovići'],
['berkovici', 'Berkovići'],
['bijeljina', 'Bijeljina'],
['bileca', 'Bileća'],
['bos-grahovo', 'Bos. Grahovo'],
['bosanska-kostajnica', 'Bosanska Kostajnica'],
['bosanska-krupa', 'Bosanska Krupa'],
['bosanski-brod', 'Bosanski Brod'],
['bosanski-petrovac', 'Bosanski Petrovac'],
['bratunac', 'Bratunac'],
['brcko', 'Brčko'],
['breza', 'Breza'],
['bugojno', 'Bugojno'],
['busovaca', 'Busovača'],
['buzim', 'Bužim'],
['cajnice', 'Čajniče'],
['capljina', 'Čapljina'],
['celic', 'Čelić'],
['celinac', 'Čelinac'],
['citluk', 'Čitluk'],
['derventa', 'Derventa'],
['doboj', 'Doboj'],
['doboj-istok', 'Doboj Istok'],
['doboj-jug', 'Doboj Jug'],
['dobretici', 'Dobretići'],
['domaljevac-samac', 'Domaljevac - Šamac'],
['donji-vakuf', 'Donji Vakuf'],
['donji-zabar', 'Donji Žabar'],
['drvar', 'Drvar'],
['foca', 'Foča'],
['foca-ustikolina', 'Foča - Ustikolina'],
['fojnica', 'Fojnica'],
['g-vakuf-uskoplje', 'G. Vakuf - Uskoplje'],
['gacko', 'Gacko'],
['glamoc', 'Glamoč'],
['gorazde', 'Goražde'],
['gracanica', 'Gračanica'],
['grad-banja-luka', 'Grad Banja Luka'],
['grad-istocno-sarajevo', 'Grad Istočno Sarajevo'],
['gradacac', 'Gradačac'],
['gradiska', 'Gradiška'],
['grude', 'Grude'],
['hadzici', 'Hadžići'],
['han-pijesak', 'Han Pijesak'],
['ilidza', 'Ilidža'],
['ilijas', 'Ilijaš'],
['istocni-drvar', 'Istočni Drvar'],
['istocni-mostar', 'Istočni Mostar'],
['istocni-stari-grad', 'Istočni Stari Grad'],
['jablanica', 'Jablanica'],
['jajce', 'Jajce'],
['jezero', 'Jezero'],
['kakanj', 'Kakanj'],
['kalesija', 'Kalesija'],
['kalinovik', 'Kalinovik'],
['kiseljak', 'Kiseljak'],
['kladanj', 'Kladanj'],
['kljuc', 'Ključ'],
['knezevo', 'Kneževo'],
['konjic', 'Konjic'],
['kotor-varos', 'Kotor Varoš'],
['kozarska-dubica', 'Kozarska Dubica'],
['kresevo', 'Kreševo'],
['krupa-na-uni', 'Krupa Na Uni'],
['kupres', 'Kupres'],
['kupres', 'Kupres'],
['laktasi', 'Laktaši'],
['livno', 'Livno'],
['ljubinje', 'Ljubinje'],
['ljubuski', 'Ljubuški'],
['lopare', 'Lopare'],
['lukavac', 'Lukavac'],
['lukavica', 'Lukavica'],
['maglaj', 'Maglaj'],
['milici', 'Milići'],
['modrica', 'Modriča'],
['mostar', 'Mostar'],
['mrkonjic-grad', 'Mrkonjić Grad'],
['neum', 'Neum'],
['nevesinje', 'Nevesinje'],
['novi-grad', 'Novi Grad'],
['novi-travnik', 'Novi Travnik'],
['odzak', 'Odžak'],
['olovo', 'Olovo'],
['opstina-istocna-ilidza', 'Opština Istočna Ilidža'],
['orasje', 'Orašje'],
['osmaci', 'Osmaci'],
['ostra-luka', 'Oštra Luka'],
['pale', 'Pale'],
['pale-praca', 'Pale - Prača'],
['pelagicevo', 'Pelagićevo'],
['petrovac', 'Petrovac'],
['petrovo', 'Petrovo'],
['posusje', 'Posušje'],
['prijedor', 'Prijedor'],
['prnjavor', 'Prnjavor'],
['prozor-rama', 'Prozor-rama'],
['ravno', 'Ravno'],
['ribnik', 'Ribnik'],
['rogatica', 'Rogatica'],
['rudo', 'Rudo'],
['samac', 'Šamac'],
['sanski-most', 'Sanski Most'],
['sapna', 'Sapna'],
['sarajevo', 'Sarajevo'],
['sekovici', 'Šekovići'],
['sipovo', 'Šipovo'],
['siroki-brijeg', 'Široki Brijeg'],
['sokolac', 'Sokolac'],
['srbac', 'Srbac'],
['srebrenica', 'Srebrenica'],
['srebrenik', 'Srebrenik'],
['stolac', 'Stolac'],
['teocak', 'Teočak'],
['tesanj', 'Tešanj'],
['teslic', 'Teslić'],
['tomislavgrad', 'Tomislavgrad'],
['travnik', 'Travnik'],
['trebinje', 'Trebinje'],
['trnovo', 'Trnovo'],
['trnovo', 'Trnovo'],
['tuzla', 'Tuzla'],
['ugljevik', 'Ugljevik'],
['usora', 'Usora'],
['ustipraca-', 'Ustiprača '],
['vares', 'Vareš'],
['velika-kladusa', 'Velika Kladuša'],
['visegrad', 'Višegrad'],
['visoko', 'Visoko'],
['vitez', 'Vitez'],
['vlasenica', 'Vlasenica'],
['vogosca', 'Vogošća'],
['vukosavlje', 'Vukosavlje'],
['zavidovici', 'Zavidovići'],
['zenica', 'Zenica'],
['zepce', 'Žepče'],
['zivinice', 'Živinice'],
['zvornik', 'Zvornik'],
];

$smarty->assign('data', $data);
$smarty->display('research.tpl');
